# Generated by Django 5.0.3 on 2024-07-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CultureQuest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='image',
            new_name='Eimage',
        ),
        migrations.RenameField(
            model_name='eventcategory',
            old_name='image',
            new_name='ECimage',
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('cash', 'Cash'), ('other', 'Other')], max_length=20),
        ),
    ]
